version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: dev_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ai_agent
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: dev_redis
    restart: always
    command: redis-server --requirepass redis123456
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123456", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s
    networks:
      - backend

networks:
  backend:
    driver: bridge
